"""Initial migration

Revision ID: 05bad1e1da21
Revises: 
Create Date: 2024-10-20 23:08:57.913070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bad1e1da21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('moves', sa.String(), nullable=True))
    op.add_column('players', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_column('players', 'username')
    op.drop_column('games', 'moves')
    # ### end Alembic commands ###
