"""add stat columns

Revision ID: 551e7e118529
Revises: 05bad1e1da21
Create Date: 2024-10-26 00:32:22.194874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551e7e118529'
down_revision: Union[str, None] = '05bad1e1da21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('first_line_moves', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('second_line_moves', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('third_line_moves', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('bad_moves', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('total_moves', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'total_moves')
    op.drop_column('games', 'bad_moves')
    op.drop_column('games', 'third_line_moves')
    op.drop_column('games', 'second_line_moves')
    op.drop_column('games', 'first_line_moves')
    # ### end Alembic commands ###
