"""Added player_color

Revision ID: 920b99c3dc99
Revises: 5a013ac8c062
Create Date: 2024-11-12 09:38:32.243690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920b99c3dc99'
down_revision: Union[str, None] = '5a013ac8c062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('player_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'player_color')
    # ### end Alembic commands ###
